collections:
  articles: '/articles/{slug}'
  blog: '/blog/{year}/{month}/{day}/{slug}'
  things: '/things/{slug}'
  sitemap: '/layouts/sitemap'
taxonomies:
  topics: '/articles/topics/{slug}'
  tags: '/blog/tags/{slug}'
routes:
  /articles/topics: topics
  /blog/tags: blog/taxonomies
  /search: search
  /users: user/index
  /users/{username}: user/profile
  /account: user/account
  /login: auth/login
  /register: auth/register
  /forgot-password: auth/password-forgot
  /reset-password: auth/password-reset
  /blog/feed:
    layout: feed
    template: feeds/blog
    content_type: atom
  /things/feed:
    layout: feed
    template: feeds/things
    content_type: atom
  /sitemap:
    template: sitemap
    layout: sitemap
    content_type: xml
  /info/hosting-and-maintenance: footer-nav-links/hosting-and-maintenance
  /info/privacy-policy: footer-nav-links/privacy-policy
  /info/sitemap: footer-nav-links/sitemap
  /info/terms-of-use: footer-nav-links/terms-of-use
  /info/web-design-agreement: footer-nav-links/web-design-agreement
  /info/web-design-process: footer-nav-links/web-design-process
